-- Eliminación de la base de datos si existe.
DROP DATABASE IF EXISTS BIKE_RENTAL_BD;

-- Creación de la base de datos.
CREATE DATABASE BIKE_RENTAL_BD DEFAULT CHARACTER SET UTF8MB4;

-- Uso de la base de datos.
USE BIKE_RENTAL_BD;

-- Crear la tabla de roles
CREATE TABLE BR_ROLES (
    ROL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROL_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE BR_USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(120) NOT NULL,
    UNIQUE (USERNAME),
    UNIQUE (EMAIL)
);


CREATE TABLE BR_USERS_ROLES (
    USER_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES BR_USERS(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES BR_ROLES(ROL_ID),
    PRIMARY KEY (USER_ID, ROLE_ID)
);


-- Crear la tabla de categorías de bicicletas con ENUM
CREATE TABLE BR_CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    CATEGORY_TYPE ENUM('MONTAÑA', 'TRABAJO', 'VIAJES', 'PASEO', 'REPARTO') NOT NULL
);

-- Crear la tabla de etiquetas
CREATE TABLE BR_TAGS (
    TAG_ID INT PRIMARY KEY AUTO_INCREMENT,
    TAG_NAME VARCHAR(50) NOT NULL
);

-- Crear la tabla de publicaciones de bicicletas
CREATE TABLE BR_POSTS (
    POST_ID INT PRIMARY KEY AUTO_INCREMENT,
    OWNER_USER_ID INT,
    CATEGORY_ID INT,
    DESCRIPTION TEXT,
    POST_NAME TEXT,
    POST_STATUS VARCHAR(50),
    CREATION_DATE DATE,
    OTHER_DETAILS VARCHAR(500),
    FOREIGN KEY (OWNER_USER_ID) REFERENCES BR_USERS (USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES BR_CATEGORIES (CATEGORY_ID)
    ON DELETE CASCADE
);

-- Crear tabla de relación entre publicaciones y etiquetas
CREATE TABLE BR_POSTS_TAGS (
    POST_ID INT,
    TAG_ID INT,
    FOREIGN KEY (POST_ID) REFERENCES BR_POSTS(POST_ID),
    FOREIGN KEY (TAG_ID) REFERENCES BR_TAGS(TAG_ID),
    PRIMARY KEY (POST_ID, TAG_ID)
);

CREATE TABLE BR_BICYCLES (
    BICYCLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    POST_ID INT,
    OWNER_USER_ID INT,
    CATEGORY_ID INT,
    BICYCLE_BRAND_MODEL VARCHAR(100),
    DESCRIPTION TEXT,
    RENTAL_PRICE DECIMAL(10, 2),
    BICYCLE_IMAGE BLOB,
    FOREIGN KEY (POST_ID) REFERENCES BR_POSTS(POST_ID)
    ON DELETE CASCADE,
    FOREIGN KEY (OWNER_USER_ID) REFERENCES BR_USERS(USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES BR_CATEGORIES (CATEGORY_ID)
);

-- Crear la tabla de alquileres de bicicletas
CREATE TABLE BR_RENTALS (
    RENTAL_ID INT PRIMARY KEY AUTO_INCREMENT,
    LANDLORD_USER_ID INT,
    TENANT_USER_ID INT,
    RENTED_BICYCLE_ID INT,
    START_DATE DATE,
    END_DATE DATE,
    RENTAL_STATUS VARCHAR(50),
    FOREIGN KEY (LANDLORD_USER_ID) REFERENCES BR_USERS(USER_ID),
    FOREIGN KEY (TENANT_USER_ID) REFERENCES BR_USERS(USER_ID),
    FOREIGN KEY (RENTED_BICYCLE_ID) REFERENCES BR_BICYCLES(BICYCLE_ID)
    ON DELETE CASCADE
);
